version: '2'
services:      
  influxdb:
    image: influxdb:2.3.0
    #image: influxdb:2.3.0-alpine
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    env_file:
      - ./config.env

  telegraf:
    image: telegraf:1.23.2
    #image: telegraf:1.23.2-alpine
    ports: 
      - 8080:8080
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - ./config.env
 
  grafana:
    image: grafana/grafana:7.5.16
    user: root
    ports: 
      - 3000:3000
    depends_on:
      - influxdb
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./config.env
