---
apiVersion: 1

policies:
  - orgId: 1
    receiver: Duplicati_Dashboard_Email
    group_by: [alertname]
    matchers:
      - alertname = Duplicati Dashboard Alert
    group_wait: 30s
    group_interval: 5m
    repeat_interval: ${NOTIFIER_EMAIL_REMINDER_FREQUENCY}
