{
 "title": "Duplicati Dashboard",
 "tags": [ "Duplicati" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Backup",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -90d)\r\n  |> filter(fn: (r) => true)\r\n  |> toString()\r\n  |> group(columns: [\"backup-name\"])\r\n  |> distinct(column: \"backup-name\")\r\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "Measurement",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementFieldKeys(\r\n  bucket: v.defaultBucket,\r\n  measurement: \"duplicati\"\r\n)\r\n"
   }
  ]
 },
 "panels": [
  { "title": "Last reported status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Backup",
   "type": "stat",
   "description": "over last 30 days",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "repeat": "Backup",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"duplicati\")\r\n  |> filter(fn: (r) => r[\"backup-name\"] == \"${Backup}\")\r\n  |> toString()\r\n  |> schema.fieldsAsCols()\r\n  |> keep(columns: [\"_time\", \"ParsedResult\"])\r\n  |> map(fn:(r) => ({ r with ParsedResult: if exists r.ParsedResult and r.ParsedResult == \"Success\" then int(v: 1) else if r.ParsedResult == \"Warning\" then int(v: 2) else int(v: 0) }))\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n  |> last(column: \"ParsedResult\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\r\nimport \"influxdata/influxdb/schema\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"duplicati\")\r\n  |> filter(fn: (r) => r[\"backup-name\"] =~ /^${Backup:pipe}/)\r\n  |> toString()\r\n  |> schema.fieldsAsCols()\r\n  |> keep(columns: [\"_time\", \"backup-name\", \"ParsedResult\", \"Message\", \"Duration\", \"BeginTime\", \"EndTime\", \"SizeOfExaminedFiles\"])\r\n  |> map(fn:(r) => ({ r with ParsedResult: if r.ParsedResult == \"Success\" then string(v: \"Success\") else if r.ParsedResult == \"Warning\" then string(v: \"Warning\") else string(v: \"Failure\") }))\r\n  |> map(fn:(r) => ({ r with Duration: if exists r.Duration then strings.substring(v: r.Duration, start: 0, end: 8) else string(v: \"\") }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last reported variations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Backup",
     "type": "stat",
     "description": "over last 30 days",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
     "repeat": "Backup",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"duplicati\")\r\n  |> filter(fn: (r) => r[\"backup-name\"] == \"${Backup}\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with\r\n    _value: (r.AddedFolders - r.DeletedFolders)\r\n  }))\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n  |> rename(columns: {_value: \"Folders: \"})\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n  |> last(column: \"_time\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"duplicati\")\r\n  |> filter(fn: (r) => r[\"backup-name\"] =~ /^${Backup:pipe}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with\r\n    _value: (r.AddedFiles - r.DeletedFiles)\r\n  }))\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n  |> rename(columns: {_value: \"Files: \"})\r\n  ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"duplicati\")\r\n  |> filter(fn: (r) => r[\"backup-name\"] =~ /^${Backup:pipe}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with\r\n    _value: (r.AddedSymlinks - r.DeletedSymlinks)\r\n  }))\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n  |> rename(columns: {_value: \"Symlinks: \"})\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n  |> last(column: \"_time\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stats : ${Backup}",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "repeat": "Backup",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"duplicati\")\r\n  |> filter(fn: (r) => r[\"backup-name\"] =~ /^${Backup}/)\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /^${Measurement:pipe}/)\r\n  |> toString()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Alerting graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerting graph",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "import \"influxdata/influxdb/schema\"\r\n\r\ndata = from(bucket: v.defaultBucket)\r\n    |> range(start: -30d)\r\n\t|> filter(fn: (r) =>\r\n\t\t(r[\"_measurement\"] == \"duplicati\"))\r\n    |> toString()\r\n    |> schema.fieldsAsCols()\r\n\t|> map(fn: (r) =>\r\n\t\t({r with ParsedResult: if exists r.ParsedResult and r.ParsedResult == \"Success\" then float(v: 1) else if r.ParsedResult == \"Warning\" then float(v: 0.5) else float(v: 0)}))\r\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"backup-name\"], valueColumn: \"ParsedResult\")\r\n    |> keep(fn: (column) => (column == \"_time\" or column !~ /^_.*/))\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n\t|> yield()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}